"""
Philosophy Discord Bot
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Auto-reageert in channel 1505313262860894308 met:
  "If [concept] is your power, what are you without it?"

App Commands (rechtermuisklik op bericht → Apps):
  • Philosophize        → stuurt de vraag als reply in het kanaal
  • Philosophize → DM   → stuurt de vraag privé naar jou
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import os
from threading import Thread

import discord
from discord import app_commands
import re
from collections import Counter
from flask import Flask

TOKEN = os.getenv("BOT_TOKEN")
TARGET_CHANNEL_ID = 1505313262860894308

# Optioneel: je server ID voor instant command-sync tijdens development.
# Laat None voor global commands (duurt ~1 uur om te verschijnen).
GUILD_ID = None  # Bijv: 123456789012345678

app = Flask(__name__)

@app.route('/')
def home():
    return "Bot is alive"

def run_web():
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)

Thread(target=run_web).start()
# ──────────────────────────────────────────────
# KEYWORD EXTRACTIE (zonder AI)
# ──────────────────────────────────────────────

STOPWORDS = {
    "i", "me", "my", "myself", "we", "our", "you", "your", "he", "she", "it",
    "they", "them", "this", "that", "the", "a", "an", "and", "or", "but",
    "in", "on", "at", "to", "for", "of", "with", "is", "are", "was", "were",
    "be", "been", "being", "have", "has", "had", "do", "does", "did", "will",
    "would", "could", "should", "may", "might", "shall", "can", "just", "so",
    "not", "no", "if", "then", "than", "too", "very", "also", "like", "as",
    "what", "who", "how", "when", "where", "why", "which", "from", "about",
    "up", "out", "into", "through", "by", "more", "some", "any", "all",
    "ik", "je", "jij", "we", "zij", "hij", "de", "het", "een", "en", "of",
    "maar", "in", "op", "aan", "voor", "van", "met", "is", "zijn", "was",
    "dat", "dit", "zich", "om", "te", "er", "al", "nog", "wel", "niet",
    "im", "its", "dont", "cant", "wont", "ive", "youre", "theyre",
    "s", "t", "m", "re", "ll", "ve", "d",
}

CONCEPT_MAP = {
    "money": "money", "wealth": "wealth", "rich": "wealth", "broke": "money",
    "fame": "fame", "popular": "popularity", "followers": "followers",
    "likes": "validation", "views": "attention", "clout": "clout",
    "success": "success", "winning": "winning", "losing": "failure",
    "power": "power", "control": "control", "strength": "strength",
    "beauty": "beauty", "looks": "your looks", "attractive": "attraction",
    "smart": "intelligence", "intelligent": "intelligence", "genius": "genius",
    "talent": "talent", "skill": "skill", "ability": "ability",
    "job": "your job", "work": "work", "career": "career", "boss": "authority",
    "title": "your title", "position": "your position", "rank": "rank",
    "friend": "your friends", "friends": "your friends", "friendship": "friendship",
    "love": "love", "relationship": "your relationship", "partner": "your partner",
    "family": "family", "parents": "your parents", "mother": "your mother",
    "father": "your father", "brother": "your brother", "sister": "your sister",
    "happy": "happiness", "happiness": "happiness", "joy": "joy",
    "sad": "sadness", "pain": "pain", "hurt": "your pain",
    "angry": "your anger", "anger": "anger", "hate": "hate",
    "fear": "fear", "anxiety": "anxiety", "stress": "stress",
    "confidence": "confidence", "ego": "your ego", "pride": "pride",
    "shame": "shame", "guilt": "guilt",
    "music": "music", "art": "art", "creativity": "creativity",
    "writing": "writing", "words": "your words", "voice": "your voice",
    "education": "education", "degree": "your degree", "school": "school",
    "knowledge": "knowledge", "wisdom": "wisdom", "truth": "truth",
    "god": "faith", "faith": "faith", "religion": "religion", "belief": "belief",
    "body": "your body", "health": "health", "fit": "fitness", "gym": "the gym",
    "food": "food", "sleep": "sleep", "rest": "rest",
    "time": "time", "age": "age", "youth": "youth", "old": "age",
    "social media": "social media", "instagram": "social media",
    "tiktok": "social media", "twitter": "social media", "phone": "your phone",
    "internet": "the internet", "technology": "technology",
    "game": "gaming", "gaming": "gaming", "sport": "sport", "sports": "sport",
    "team": "your team", "player": "being a player",
    "leader": "leadership", "leadership": "leadership",
    "freedom": "freedom", "choice": "choice", "decision": "your decisions",
    "past": "your past", "future": "your future", "memory": "your memories",
    "trauma": "your trauma", "story": "your story", "name": "your name",
    "reputation": "reputation", "image": "your image", "brand": "your brand",
    "race": "race", "gender": "gender", "identity": "identity",
    "culture": "culture", "roots": "your roots", "language": "language",
    "home": "home", "place": "your place", "city": "your city",
    "dream": "your dreams", "goal": "your goals", "ambition": "ambition",
    "hope": "hope", "purpose": "purpose", "meaning": "meaning",
    "life": "life", "death": "death", "existence": "existence",
    "opinion": "your opinions", "ideas": "your ideas", "thoughts": "your thoughts",
    "humor": "humor", "funny": "humor", "laugh": "laughter",
    "attention": "attention", "recognition": "recognition",
    "respect": "respect", "honor": "honor",
    "loneliness": "loneliness", "alone": "being alone", "isolation": "isolation",
    "connection": "connection", "belonging": "belonging",
    "discipline": "discipline", "routine": "your routine", "habit": "your habits",
    "mind": "your mind", "heart": "your heart", "soul": "your soul",
    "privilege": "privilege", "luck": "luck",
    "struggle": "your struggle", "hustle": "the hustle", "nigger": "racism to black people",
    "socrates": "getting ragebaited", "femboys": "gooning to femboys", "femboy": "gooning to femboys",
    "nigga": "racism to black people", "niggers": "racism to black people", "nig": "racism to black people",
    "nga": "racism to black people", "gooning": "gooning", "goon": "gooning", "Geometry Dash": "gooning to femboys", "geometry dash": "gooning to femboys",
    "reference": "Nine Circles", "florr": "not touching grass", "flor": "not touching grass", "florrr": "not touching grass",
    "Cubing_Pro": "math", "cubing_pro": "math", "cubingpro": "math", "cubing_hater": "unemployedness",
    "cubing hater": "unemployedness", "cubinghater": "unemployedness",
    "Marcel Rudge": "your basement", "marcel rudge": "your basement", "marcel": "your basement", "mr": "your basement",
    "fmmr": "your basement", "pong": "youtube", "nya": "being a furry", "furry": "being a furry", "furries": "being a furry",
    "meow": "being a furry", "purr": "being a furry", "cat": "being a furry", "dog": "being a furry",
    "David": "leaking everything", "david": "leaking everything", "davidaa": "leaking everything",
    "Stierstraat 11": "leaking everything", "stierstraat 11": "leaking everything", "stierstraat11": "leaking everything",
    "Moeshie": "cuteness", "moeshie": "cuteness", "moe": "cuteness", "shie": "cuteness", "@core_cyan": "skullbait",
    "core_cyan": "skullbait", "Core_Cyan": "skullbait", "Core_cyan": "skullbait", "core_Cyan": "skullbait",
    "corecyan": "skullbait", "CoreCyan": "skullbait", "corecyan": "skullbait",
    "“You will die in a house fire” said the oracle. I am a shrimp. I live in the ocean. And house fires cannot start in the ocean. Today I left my house to do my shrimpy business, like all shrimps do. When I returned home, I decided to go play some florr.io to relax myself and have some fun. Then I decided to go see the oracle because why not. “You will die in a house fire” said the oracle again. Surely this had to be false. Then I smelt something burning. The smell of smoke only grew bigger. Eventually I decided to check where the smoke was coming from, and guess what? It was coming from my house. Fearing for my life, I decided to escape my house, but all the exits were blocked. How is this possible? House fires cannot start in the ocean, but how did I have one anyway? Was I really going to die? Am I really going to face my worst nightmare? Becoming a fried shrimp?": "being a fried shrimp",
    "house fires cannot start in the ocean": "being a fried shrimp",
    "stole": "stealing", "steal": "stealing", "stole from": "stealing", "stole my": "stealing", "stole your": "stealing", "stole his": "stealing", "stole her": "stealing", "stole their": "stealing", "stole our": "stealing", "stole the": "stealing",
    "suiko": "blood",

    "verified": "being verified", "checkmark": "your checkmark",
    "subscribers": "your subscribers", "subscribers": "your audience",
    "retweets": "attention", "shares": "your reach", "viral": "going viral",
    "influencer": "your influence", "content": "your content",
    "creator": "being a creator", "streamer": "streaming",
    "platform": "your platform", "algorithm": "the algorithm",
    "engagement": "engagement", "analytics": "your numbers",
    "monetize": "monetization", "sponsorship": "sponsorships",
    "collab": "collaboration", "network": "your network",
    "exposure": "exposure", "branding": "your brand",
    "aesthetic": "your aesthetic", "feed": "your feed",
    "highlight": "your highlights", "story": "your story",
    "niche": "your niche", "audience": "your audience",
    "comment": "your comments", "reply": "your replies",
    "notification": "notifications", "badge": "your badge",

    "salary": "your salary", "income": "income", "debt": "your debt",
    "loan": "loans", "credit": "credit", "savings": "your savings",
    "investment": "investments", "stock": "stocks", "crypto": "crypto",
    "bitcoin": "bitcoin", "nft": "NFTs", "asset": "your assets",
    "property": "property", "house": "your house", "car": "your car",
    "luxury": "luxury", "designer": "designer labels", "brand": "your brand",
    "expensive": "expensive things", "cheap": "being cheap",
    "profit": "profit", "loss": "your losses", "budget": "your budget",
    "tip": "tips", "bonus": "your bonus", "raise": "your raise",
    "promotion": "your promotion", "contract": "your contract",

    "ex": "your ex", "crush": "your crush", "date": "dating",
    "marriage": "marriage", "divorce": "divorce", "single": "being single",
    "loyalty": "loyalty", "betrayal": "betrayal", "trust": "trust",
    "jealousy": "jealousy", "envy": "envy", "gossip": "gossip",
    "drama": "drama", "conflict": "conflict", "argument": "your arguments",
    "apology": "your apologies", "forgiveness": "forgiveness",
    "boundary": "your boundaries", "toxic": "toxicity",
    "support": "support", "validation": "validation", "approval": "approval",
    "rejection": "rejection", "acceptance": "acceptance",
    "community": "community", "tribe": "your tribe",
    "crowd": "the crowd", "popularity": "popularity",
    "social": "your social life", "networking": "networking",
    "mentorship": "mentorship", "mentor": "your mentor",
    "influence": "your influence", "peer": "your peers",
    "competition": "competition", "rivalry": "rivalry",
    "enemy": "your enemies", "hater": "your haters", "fan": "your fans",
    "follower": "your followers", "idol": "your idols",

    "honesty": "honesty", "integrity": "integrity", "loyalty": "loyalty",
    "courage": "courage", "bravery": "bravery", "coward": "cowardice",
    "kindness": "kindness", "compassion": "compassion", "empathy": "empathy",
    "patience": "patience", "gratitude": "gratitude", "humility": "humility",
    "arrogance": "arrogance", "narcissism": "narcissism",
    "insecurity": "your insecurities", "doubt": "your doubts",
    "overthinking": "overthinking", "worry": "your worries",
    "regret": "regret", "nostalgia": "nostalgia", "bitterness": "bitterness",
    "resilience": "resilience", "persistence": "persistence",
    "determination": "determination", "willpower": "willpower",
    "motivation": "motivation", "inspiration": "inspiration",
    "creativity": "creativity", "curiosity": "curiosity",
    "passion": "passion", "obsession": "obsession",
    "addiction": "addiction", "habit": "your habits",
    "routine": "your routine", "comfort": "comfort",
    "vulnerability": "vulnerability", "authenticity": "authenticity",
    "charisma": "charisma", "charm": "charm", "wit": "wit",
    "sarcasm": "sarcasm", "irony": "irony",

    "weight": "your weight", "diet": "your diet", "calories": "calories",
    "muscle": "muscle", "fat": "body fat", "skinny": "being skinny",
    "workout": "working out", "exercise": "exercise", "cardio": "cardio",
    "running": "running", "lifting": "lifting", "yoga": "yoga",
    "meditation": "meditation", "breathing": "your breathing",
    "sobriety": "sobriety", "drugs": "drugs", "alcohol": "alcohol",
    "smoking": "smoking", "drinking": "drinking",
    "therapy": "therapy", "healing": "healing", "recovery": "recovery",
    "sickness": "sickness", "illness": "illness", "disability": "disability",
    "surgery": "surgery", "medication": "medication",
    "mental health": "mental health", "depression": "depression",
    "self-worth": "self-worth", "self-love": "self-love",
    "self-care": "self-care", "burnout": "burnout",
    "exhaustion": "exhaustion", "energy": "your energy",
    "adrenaline": "adrenaline", "dopamine": "dopamine",

    "grades": "your grades", "gpa": "your GPA", "exam": "exams",
    "test": "tests", "diploma": "your diploma", "certificate": "certificates",
    "award": "awards", "trophy": "trophies", "medal": "medals",
    "record": "your record", "achievement": "achievements",
    "milestone": "milestones", "progress": "progress", "growth": "growth",
    "improvement": "improvement", "potential": "your potential",
    "opportunity": "opportunity", "chance": "your chances",
    "risk": "risk", "gamble": "gambling", "bet": "your bets",
    "plan": "your plans", "strategy": "strategy", "vision": "your vision",
    "mission": "your mission", "legacy": "your legacy",
    "impact": "impact", "contribution": "your contribution",
    "change": "change", "revolution": "revolution", "movement": "the movement",

    "morality": "morality", "ethics": "ethics", "justice": "justice",
    "fairness": "fairness", "equality": "equality", "privilege": "privilege",
    "suffering": "suffering", "sacrifice": "sacrifice", "loss": "loss",
    "grief": "grief", "emptiness": "emptiness", "void": "the void",
    "silence": "silence", "darkness": "darkness", "light": "light",
    "shadow": "your shadow", "reflection": "your reflection",
    "perception": "perception", "reality": "reality", "illusion": "illusion",
    "ego": "your ego", "soul": "your soul", "spirit": "your spirit",
    "karma": "karma", "fate": "fate", "destiny": "destiny",
    "luck": "luck", "coincidence": "coincidence", "universe": "the universe",
    "universe": "the universe", "chaos": "chaos", "order": "order",
    "balance": "balance", "harmony": "harmony", "peace": "peace",
    "war": "war", "violence": "violence", "anger": "anger",
    "revolution": "revolution", "system": "the system",
    "structure": "structure", "rule": "rules", "law": "the law",
    "authority": "authority", "obedience": "obedience", "rebellion": "rebellion",
    "conformity": "conformity", "individuality": "individuality",
    "originality": "originality", "uniqueness": "being unique",
    "normality": "normality", "weirdness": "your weirdness",

    "score": "the score", "rank": "your rank", "rating": "your rating",
    "level": "your level", "tier": "your tier", "league": "your league",
    "championship": "the championship", "title": "your title",
    "draft": "the draft", "contract": "your contract",
    "stats": "your stats", "performance": "performance",
    "training": "training", "practice": "practice", "coach": "your coach",
    "captain": "being captain", "starter": "being a starter",
    "bench": "the bench", "substitute": "being a substitute",
    "underdog": "being the underdog", "favorite": "being the favorite",
    "comeback": "the comeback", "defeat": "defeat", "victory": "victory",

    "startup": "your startup", "business": "your business",
    "entrepreneur": "entrepreneurship", "hustle": "the hustle",
    "grind": "the grind", "side hustle": "your side hustle",
    "passive income": "passive income", "freelance": "freelancing",
    "remote": "remote work", "office": "the office",
    "meeting": "meetings", "deadline": "deadlines", "project": "your project",
    "client": "your clients", "customer": "your customers",
    "product": "your product", "service": "your service",
    "feedback": "feedback", "review": "reviews", "rating": "your rating",
    "reputation": "reputation", "credibility": "credibility",
    "expertise": "expertise", "experience": "experience",
    "internship": "internships", "interview": "interviews",
    "resume": "your resume", "portfolio": "your portfolio",
    "reference": "references", "recommendation": "recommendations",

    "code": "code", "coding": "coding", "programming": "programming",
    "hacking": "hacking", "software": "software", "hardware": "hardware",
    "data": "data", "ai": "AI slop", "robot": "robots",
    "automation": "automation", "algorithm": "algorithms",
    "minecraft": "Minecraft", "fortnite": "Fortnite", "ranked": "ranked",
    "meta": "the meta", "loadout": "your loadout", "build": "your build",
    "kill": "your kills", "death": "your deaths", "win rate": "your win rate",
    "clutch": "the clutch", "carry": "carrying", "toxic": "toxicity",
    "noob": "being called a noob", "pro": "being a pro",
    "esports": "esports", "tournament": "tournaments",

    "nature": "nature", "earth": "the earth", "ocean": "the ocean",
    "mountain": "the mountain", "forest": "the forest", "fire": "fire",
    "water": "water", "air": "air", "storm": "the storm",
    "sun": "the sun", "moon": "the moon", "stars": "the stars",
    "energy": "energy", "vibration": "your vibration", "frequency": "frequency",
    "manifestation": "manifestation", "law of attraction": "the law of attraction",
    "mindfulness": "mindfulness", "gratitude": "gratitude",
    "chakra": "your chakras", "aura": "your aura",
    "intuition": "intuition", "instinct": "instinct",
    "signs": "signs", "synchronicity": "synchronicity",

    "opinion": "your opinion", "perspective": "your perspective",
    "narrative": "your narrative", "excuse": "your excuses",
    "blame": "blame", "victim": "victimhood", "survivor": "survival",
    "mask": "your mask", "facade": "your facade", "role": "your role",
    "label": "labels", "stereotype": "stereotypes", "assumption": "assumptions",
    "expectation": "expectations", "pressure": "pressure",
    "standard": "standards", "norm": "norms", "tradition": "tradition",
    "change": "change", "growth": "growth", "transformation": "transformation",
    "awakening": "awakening", "realization": "realization",
    "clarity": "clarity", "confusion": "confusion", "uncertainty": "uncertainty",
    "answer": "your answers", "question": "your questions",
    "secret": "your secrets", "lie": "your lies", "truth": "truth",
    "promise": "your promises", "commitment": "commitment",
    "discipline": "discipline", "sacrifice": "sacrifice",
    "obsession": "obsession", "fixation": "fixation",

    "钱": "money", "财富": "wealth", "成功": "success",
    "名声": "fame", "权力": "power", "地位": "status",
    "面子": "face", "荣誉": "honor", "尊重": "respect",
    "家庭": "family", "爱": "love", "友谊": "friendship",
    "朋友": "your friends", "父母": "your parents", "孩子": "your children",
    "健康": "health", "美丽": "beauty", "身体": "your body",
    "工作": "work", "事业": "career", "学历": "your degree",
    "知识": "knowledge", "智慧": "wisdom", "才华": "talent",
    "梦想": "your dreams", "目标": "your goals", "未来": "your future",
    "过去": "your past", "记忆": "your memories", "希望": "hope",
    "自由": "freedom", "选择": "choice", "命运": "destiny",
    "运气": "luck", "机会": "opportunity", "努力": "hard work",
    "坚持": "persistence", "勇气": "courage", "信心": "confidence",
    "骄傲": "pride", "谦虚": "humility", "善良": "kindness",
    "诚实": "honesty", "忠诚": "loyalty", "信任": "trust",
    "嫉妒": "jealousy", "恐惧": "fear", "痛苦": "pain",
    "孤独": "loneliness", "快乐": "happiness", "平静": "peace",
    "意义": "meaning", "目的": "purpose", "灵魂": "your soul",
    "身份": "identity", "文化": "culture", "根": "your roots",
    "语言": "language", "家": "home", "归属感": "belonging",
    "社会": "society", "规则": "rules", "权威": "authority",
    "变化": "change", "成长": "growth", "进步": "progress",
    "创造力": "creativity", "艺术": "art", "音乐": "music",
    "时间": "time", "年龄": "age", "死亡": "death",
    "生命": "life", "存在": "existence", "真相": "truth",
    "道德": "morality", "正义": "justice", "平等": "equality",
    "牺牲": "sacrifice", "奉献": "dedication", "责任": "responsibility",
    "压力": "pressure", "期望": "expectations", "标准": "standards",
    "完美": "perfection", "失败": "failure", "胜利": "victory",
    "竞争": "competition", "成就": "achievement", "荣耀": "glory",
    "影响力": "influence", "领导力": "leadership", "团队": "your team",
    "控制": "control", "力量": "strength", "意志力": "willpower",
    "激情": "passion", "执着": "obsession", "习惯": "your habits",
    "纪律": "discipline", "自律": "self-discipline", "自我": "your ego",
    "内心": "your inner self", "价值观": "your values",

    "geld": "money", "rijkdom": "wealth", "succes": "success",
    "roem": "fame", "macht": "power", "status": "status",
    "eer": "honor", "respect": "respect", "waardigheid": "dignity",
    "familie": "family", "liefde": "love", "vriendschap": "friendship",
    "vrienden": "your friends", "ouders": "your parents", "kinderen": "your children",
    "gezondheid": "health", "schoonheid": "beauty", "lichaam": "your body",
    "werk": "work", "carrière": "career", "opleiding": "your education",
    "kennis": "knowledge", "wijsheid": "wisdom", "talent": "talent",
    "dromen": "your dreams", "doelen": "your goals", "toekomst": "your future",
    "verleden": "your past", "herinneringen": "your memories", "hoop": "hope",
    "vrijheid": "freedom", "keuze": "choice", "lot": "destiny",
    "geluk": "luck", "kans": "opportunity", "doorzettingsvermogen": "persistence",
    "moed": "courage", "zelfvertrouwen": "confidence", "trots": "pride",
    "bescheidenheid": "humility", "vriendelijkheid": "kindness",
    "eerlijkheid": "honesty", "loyaliteit": "loyalty", "vertrouwen": "trust",
    "jaloezie": "jealousy", "angst": "fear", "pijn": "pain",
    "eenzaamheid": "loneliness", "geluk": "happiness", "rust": "peace",
    "betekenis": "meaning", "doel": "purpose", "ziel": "your soul",
    "identiteit": "identity", "cultuur": "culture", "wortels": "your roots",
    "taal": "language", "thuis": "home", "verbondenheid": "belonging",
    "samenleving": "society", "regels": "rules", "autoriteit": "authority",
    "verandering": "change", "groei": "growth", "vooruitgang": "progress",
    "creativiteit": "creativity", "kunst": "art", "muziek": "music",
    "tijd": "time", "leeftijd": "age", "dood": "death",
    "leven": "life", "bestaan": "existence", "waarheid": "truth",
    "moraliteit": "morality", "rechtvaardigheid": "justice", "gelijkheid": "equality",
    "opoffering": "sacrifice", "toewijding": "dedication", "verantwoordelijkheid": "responsibility",
    "druk": "pressure", "verwachtingen": "expectations", "normen": "standards",
    "perfectie": "perfection", "mislukking": "failure", "overwinning": "victory",
    "concurrentie": "competition", "prestatie": "achievement", "glorie": "glory",
    "invloed": "influence", "leiderschap": "leadership", "team": "your team",
    "controle": "control", "kracht": "strength", "wilskracht": "willpower",
    "passie": "passion", "obsessie": "obsession", "gewoonten": "your habits",
    "discipline": "discipline", "ego": "your ego", "zelfbeeld": "your self-image",
    "waarden": "your values", "karakter": "character",

    "dinero": "money", "riqueza": "wealth", "éxito": "success",
    "fama": "fame", "poder": "power", "estatus": "status",
    "honor": "honor", "respeto": "respect", "dignidad": "dignity",
    "familia": "family", "amor": "love", "amistad": "friendship",
    "amigos": "your friends", "padres": "your parents", "hijos": "your children",
    "salud": "health", "belleza": "beauty", "cuerpo": "your body",
    "trabajo": "work", "carrera": "career", "educación": "your education",
    "conocimiento": "knowledge", "sabiduría": "wisdom", "talento": "talent",
    "sueños": "your dreams", "metas": "your goals", "futuro": "your future",
    "pasado": "your past", "recuerdos": "your memories", "esperanza": "hope",
    "libertad": "freedom", "elección": "choice", "destino": "destiny",
    "suerte": "luck", "oportunidad": "opportunity", "persistencia": "persistence",
    "valentía": "courage", "confianza": "confidence", "orgullo": "pride",
    "humildad": "humility", "bondad": "kindness", "honestidad": "honesty",
    "lealtad": "loyalty", "confianza": "trust", "celos": "jealousy",
    "miedo": "fear", "dolor": "pain", "soledad": "loneliness",
    "felicidad": "happiness", "paz": "peace", "significado": "meaning",
    "propósito": "purpose", "alma": "your soul", "identidad": "identity",
    "cultura": "culture", "raíces": "your roots", "idioma": "language",
    "hogar": "home", "pertenencia": "belonging", "sociedad": "society",
    "reglas": "rules", "autoridad": "authority", "cambio": "change",
    "crecimiento": "growth", "progreso": "progress", "creatividad": "creativity",
    "arte": "art", "música": "music", "tiempo": "time",
    "edad": "age", "muerte": "death", "vida": "life",
    "existencia": "existence", "verdad": "truth", "moralidad": "morality",
    "justicia": "justice", "igualdad": "equality", "sacrificio": "sacrifice",
    "dedicación": "dedication", "responsabilidad": "responsibility",
    "presión": "pressure", "expectativas": "expectations", "estándares": "standards",
    "perfección": "perfection", "fracaso": "failure", "victoria": "victory",
    "competencia": "competition", "logro": "achievement", "gloria": "glory",
    "influencia": "influence", "liderazgo": "leadership", "equipo": "your team",
    "control": "control", "fuerza": "strength", "fuerza de voluntad": "willpower",
    "pasión": "passion", "obsesión": "obsession", "hábitos": "your habits",
    "disciplina": "discipline", "ego": "your ego", "valores": "your values",
    "carácter": "character", "reputación": "reputation",

    "perfectionist": "perfectionism", "people pleaser": "people pleasing",
    "overachiever": "overachieving", "underachiever": "underachieving",
    "introvert": "being an introvert", "extrovert": "being an extrovert",
    "empath": "being an empath", "loner": "being a lone wolf",
    "rebel": "rebellion", "conformist": "conformity",
    "optimist": "optimism", "pessimist": "pessimism", "realist": "realism",
    "idealist": "idealism", "nihilist": "nihilism", "stoic": "stoicism",
    "minimalist": "minimalism", "maximalist": "excess",
    "workaholic": "being a workaholic", "perfectionism": "perfectionism",
    "procrastination": "procrastination", "laziness": "laziness",
    "ambition": "ambition", "complacency": "complacency",
    "self-discipline": "self-discipline", "self-sabotage": "self-sabotage",
    "self-awareness": "self-awareness", "self-deception": "self-deception",
    "self-improvement": "self-improvement", "self-destruction": "self-destruction",
    "self-expression": "self-expression", "self-suppression": "self-suppression",
    "self-reliance": "self-reliance", "self-doubt": "self-doubt",
    "self-respect": "self-respect", "self-neglect": "self-neglect",
    "self-acceptance": "self-acceptance", "self-rejection": "self-rejection",
    "self-pity": "self-pity", "self-compassion": "self-compassion",
    "ego death": "ego death", "ego boost": "ego boosts",
    "identity crisis": "identity crisis", "midlife crisis": "a midlife crisis",
    "quarter life crisis": "a quarter-life crisis",
    "imposter syndrome": "imposter syndrome", "savior complex": "savior complex",
    "victim mentality": "victim mentality", "survivor mentality": "survival",
    "growth mindset": "growth mindset", "fixed mindset": "a fixed mindset",
    "scarcity mindset": "a scarcity mindset", "abundance mindset": "abundance",

    "clique": "your clique", "squad": "your squad", "crew": "your crew",
    "gang": "your gang", "circle": "your circle", "inner circle": "your inner circle",
    "outsider": "being an outsider", "insider": "being an insider",
    "belong": "belonging", "outcast": "being an outcast",
    "misfit": "being a misfit", "underdog": "being the underdog",
    "overdog": "being on top", "gatekeeper": "gatekeeping",
    "influencer": "your influence", "follower": "your followers",
    "trendsetter": "setting trends", "trend follower": "following trends",
    "pioneer": "pioneering", "imitator": "imitation",
    "original": "originality", "copy": "copying others",
    "authentic": "authenticity", "fake": "being fake",
    "genuine": "genuineness", "performative": "performance",
    "vulnerable": "vulnerability", "guarded": "your walls",
    "open": "openness", "closed off": "being closed off",
    "approachable": "being approachable", "intimidating": "intimidation",
    "likeable": "likeability", "unlikeable": "being disliked",
    "charismatic": "charisma", "awkward": "awkwardness",
    "social anxiety": "social anxiety", "social confidence": "social confidence",
    "small talk": "small talk", "deep talk": "deep conversation",
    "networking": "networking", "isolation": "isolation",
    "community": "community", "tribe": "your tribe",
    "echo chamber": "your echo chamber", "bubble": "your bubble",
    "cancel culture": "cancel culture", "call out": "calling people out",
    "accountability": "accountability", "consequence": "consequences",
    "reputation management": "managing your reputation",
    "public image": "your public image", "persona": "your persona",
    "alter ego": "your alter ego", "true self": "your true self",

    "dominance": "dominance", "submission": "submission",
    "manipulation": "manipulation", "gaslighting": "gaslighting",
    "coercion": "coercion", "persuasion": "persuasion",
    "negotiation": "negotiation", "compromise": "compromise",
    "ultimatum": "ultimatums", "boundaries": "your boundaries",
    "leverage": "leverage", "advantage": "your advantage",
    "weakness": "your weakness", "vulnerability": "vulnerability",
    "shield": "your shield", "armor": "your armor",
    "weapon": "your weapons", "defense": "your defenses",
    "offense": "your offense", "strategy": "strategy",
    "tactics": "tactics", "mind games": "mind games",
    "power play": "power plays", "chess": "playing chess",
    "checkmate": "checkmate", "surrender": "surrender",
    "resistance": "resistance", "compliance": "compliance",
    "defiance": "defiance", "obedience": "obedience",
    "autonomy": "autonomy", "dependency": "dependency",
    "codependency": "codependency", "independence": "independence",
    "interdependence": "interdependence", "self-sufficiency": "self-sufficiency",
    "need": "your needs", "want": "your wants", "desire": "desire",
    "craving": "your cravings", "impulse": "your impulses",
    "temptation": "temptation", "willpower": "willpower",
    "restraint": "restraint", "indulgence": "indulgence",

    "imagination": "imagination", "vision": "your vision",
    "innovation": "innovation", "invention": "invention",
    "discovery": "discovery", "exploration": "exploration",
    "experimentation": "experimentation", "risk taking": "risk-taking",
    "storytelling": "storytelling", "narrative": "your narrative",
    "poetry": "poetry", "prose": "prose", "lyrics": "your lyrics",
    "melody": "melody", "rhythm": "rhythm", "beat": "the beat",
    "harmony": "harmony", "dissonance": "dissonance",
    "composition": "composition", "improvisation": "improvisation",
    "performance": "performance", "audience": "your audience",
    "applause": "applause", "silence": "silence",
    "critique": "critique", "praise": "praise",
    "criticism": "criticism", "feedback": "feedback",
    "revision": "revision", "perfectionism": "perfectionism",
    "inspiration": "inspiration", "block": "creative block",
    "flow": "flow state", "momentum": "momentum",
    "craft": "your craft", "medium": "your medium",
    "canvas": "your canvas", "instrument": "your instrument",
    "stage": "the stage", "spotlight": "the spotlight",
    "curtain call": "the curtain call", "encore": "the encore",
    "legacy": "your legacy", "masterpiece": "your masterpiece",
    "magnum opus": "your magnum opus", "debut": "your debut",
    "breakthrough": "your breakthrough", "plateau": "your plateau",
    "evolution": "your evolution", "revolution": "revolution",

    "overthinking": "overthinking", "rumination": "rumination",
    "intrusive thoughts": "intrusive thoughts", "racing mind": "a racing mind",
    "mental fog": "mental fog", "clarity": "clarity",
    "grounding": "being grounded", "dissociation": "dissociation",
    "hypervigilance": "hypervigilance", "numbness": "numbness",
    "emotional labor": "emotional labor", "compassion fatigue": "compassion fatigue",
    "empathy": "empathy", "sympathy": "sympathy",
    "detachment": "detachment", "attachment": "attachment",
    "avoidance": "avoidance", "confrontation": "confrontation",
    "suppression": "suppression", "expression": "expression",
    "catharsis": "catharsis", "release": "release",
    "tension": "tension", "relief": "relief",
    "overwhelm": "feeling overwhelmed", "underwhelm": "being underwhelmed",
    "boredom": "boredom", "excitement": "excitement",
    "anticipation": "anticipation", "dread": "dread",
    "euphoria": "euphoria", "dysphoria": "dysphoria",
    "mania": "mania", "depression": "depression",
    "mood": "your mood", "temperament": "your temperament",
    "emotional intelligence": "emotional intelligence",
    "emotional regulation": "emotional regulation",
    "coping": "coping", "coping mechanism": "your coping mechanisms",
    "trigger": "your triggers", "response": "your responses",
    "reaction": "your reactions", "impulse control": "impulse control",
    "patience": "patience", "impatience": "impatience",
    "frustration": "frustration", "irritability": "irritability",
    "rage": "rage", "fury": "fury", "resentment": "resentment",
    "bitterness": "bitterness", "envy": "envy", "spite": "spite",
    "malice": "malice", "cruelty": "cruelty", "sadism": "sadism",
    "masochism": "masochism", "suffering": "suffering",
    "martyrdom": "martyrdom", "sacrifice": "sacrifice",

    "enlightenment": "enlightenment", "awakening": "awakening",
    "consciousness": "consciousness", "awareness": "awareness",
    "presence": "being present", "mindfulness": "mindfulness",
    "surrender": "surrender", "acceptance": "acceptance",
    "letting go": "letting go", "holding on": "holding on",
    "attachment": "attachment", "detachment": "detachment",
    "impermanence": "impermanence", "permanence": "permanence",
    "change": "change", "constancy": "constancy",
    "flow": "going with the flow", "resistance": "resistance",
    "alignment": "alignment", "misalignment": "being misaligned",
    "purpose": "purpose", "calling": "your calling",
    "mission": "your mission", "vision": "your vision",
    "devotion": "devotion", "dedication": "dedication",
    "prayer": "prayer", "meditation": "meditation",
    "ritual": "ritual", "ceremony": "ceremony",
    "gratitude": "gratitude", "abundance": "abundance",
    "manifestation": "manifestation", "intention": "intention",
    "affirmation": "affirmations", "visualization": "visualization",
    "higher self": "your higher self", "inner child": "your inner child",
    "shadow self": "your shadow self", "subconscious": "your subconscious",
    "collective consciousness": "collective consciousness",
    "oneness": "oneness", "separation": "separation",
    "duality": "duality", "unity": "unity",
    "transcendence": "transcendence", "immanence": "immanence",
    "eternity": "eternity", "mortality": "mortality",
    "rebirth": "rebirth", "renewal": "renewal",
    "redemption": "redemption", "salvation": "salvation",
    "sin": "sin", "virtue": "virtue", "grace": "grace",
    "mercy": "mercy", "judgment": "judgment", "forgiveness": "forgiveness",

    "environment": "your environment", "surroundings": "your surroundings",
    "neighborhood": "your neighborhood", "city life": "city life",
    "country life": "country life", "nature": "nature",
    "seasons": "the seasons", "weather": "the weather",
    "climate": "climate", "landscape": "the landscape",
    "roots": "your roots", "soil": "the soil you grew from",
    "foundation": "your foundation", "structure": "structure",
    "architecture": "architecture", "design": "design",
    "space": "your space", "territory": "your territory",
    "borders": "borders", "walls": "your walls",
    "doors": "doors", "windows": "windows",
    "comfort zone": "your comfort zone", "safe space": "your safe space",
    "danger zone": "danger", "unknown": "the unknown",
    "frontier": "the frontier", "horizon": "the horizon",
    "journey": "your journey", "destination": "your destination",
    "path": "your path", "crossroads": "the crossroads",
    "detour": "detours", "shortcut": "shortcuts",
    "obstacle": "obstacles", "barrier": "barriers",
    "bridge": "bridges", "gap": "the gap",
    "distance": "distance", "closeness": "closeness",
    "proximity": "proximity", "separation": "separation",

    "algorithm": "the algorithm", "data": "your data",
    "privacy": "privacy", "surveillance": "surveillance",
    "digital footprint": "your digital footprint",
    "online presence": "your online presence",
    "screen time": "screen time", "digital detox": "digital detox",
    "notification": "notifications", "dopamine hit": "dopamine hits",
    "scroll": "scrolling", "doom scrolling": "doom scrolling",
    "content consumption": "content consumption",
    "content creation": "content creation", "creator economy": "the creator economy",
    "side hustle": "your side hustle", "passive income": "passive income",
    "financial freedom": "financial freedom", "fire movement": "financial independence",
    "minimalism": "minimalism", "declutter": "decluttering",
    "productivity": "productivity", "efficiency": "efficiency",
    "optimization": "optimization", "biohacking": "biohacking",
    "quantified self": "self-quantification", "tracking": "tracking yourself",
    "metrics": "your metrics", "kpis": "your KPIs",
    "benchmark": "your benchmarks", "baseline": "your baseline",
    "upgrade": "upgrading", "update": "updating",
    "version": "your current version", "obsolete": "becoming obsolete",
    "disruption": "disruption", "innovation": "innovation",
    "startup culture": "startup culture", "hustle culture": "hustle culture",
    "grind culture": "grind culture", "burnout culture": "burnout culture",
    "toxic positivity": "toxic positivity", "gaslighting": "gaslighting",
    "echo chamber": "your echo chamber", "filter bubble": "your filter bubble",
    "tribalism": "tribalism", "polarization": "polarization",
    "cancel": "cancel culture", "woke": "being woke",
    "virtue signaling": "virtue signaling", "performative activism": "performative activism",

    "athletic ability": "athletic ability", "natural talent": "natural talent",
    "work ethic": "work ethic", "raw talent": "raw talent",
    "coachability": "being coachable", "leadership": "leadership",
    "clutch performance": "clutch performance", "choking": "choking under pressure",
    "momentum": "momentum", "home advantage": "home advantage",
    "crowd energy": "crowd energy", "pressure": "pressure",
    "pressure performance": "performing under pressure",
    "consistency": "consistency", "peak performance": "peak performance",
    "longevity": "longevity", "prime": "your prime",
    "decline": "your decline", "retirement": "retirement",
    "comeback": "the comeback", "redemption arc": "your redemption arc",
    "goat": "being the GOAT", "legend": "being a legend",
    "hall of fame": "the hall of fame", "legacy": "your legacy",
    "dynasty": "dynasty", "era": "your era",
    "game": "the game", "sport": "sport", "play": "playing",
    "competition": "competition", "collaboration": "collaboration",
    "individual": "individual glory", "team": "teamwork",
    "sacrifice for team": "sacrificing for the team",
    "personal glory": "personal glory", "collective success": "collective success",

    "net worth": "your net worth", "cash flow": "cash flow",
    "liquidity": "liquidity", "solvency": "solvency",
    "bankruptcy": "bankruptcy", "abundance": "abundance",
    "scarcity": "scarcity", "poverty": "poverty", "wealth gap": "the wealth gap",
    "inheritance": "your inheritance", "generational wealth": "generational wealth",
    "first generation": "being first generation", "old money": "old money",
    "new money": "new money", "self made": "being self-made",
    "bootstrapped": "bootstrapping", "funded": "being funded",
    "investor": "investors", "venture capital": "venture capital",
    "valuation": "your valuation", "exit": "the exit",
    "equity": "equity", "ownership": "ownership",
    "shareholder": "being a shareholder", "stakeholder": "being a stakeholder",
    "dividend": "dividends", "return": "returns",
    "compound interest": "compound interest", "time value": "time",
    "opportunity cost": "opportunity cost", "sunk cost": "sunk cost fallacy",
    "loss aversion": "loss aversion", "risk tolerance": "risk tolerance",
    "diversification": "diversification", "hedging": "hedging your bets",
    "speculation": "speculation", "arbitrage": "arbitrage",
    "leverage": "leverage", "margin": "margin",

    "attachment style": "your attachment style", "anxious attachment": "anxious attachment",
    "avoidant attachment": "avoidant attachment", "secure attachment": "secure attachment",
    "love language": "your love language", "quality time": "quality time",
    "words of affirmation": "words of affirmation", "acts of service": "acts of service",
    "physical touch": "physical touch", "gift giving": "gift giving",
    "emotional availability": "emotional availability",
    "emotional unavailability": "emotional unavailability",
    "vulnerability": "vulnerability", "intimacy": "intimacy",
    "commitment": "commitment", "fear of commitment": "fear of commitment",
    "abandonment": "fear of abandonment", "rejection sensitivity": "rejection sensitivity",
    "people pleasing": "people pleasing", "fawning": "fawning",
    "codependency": "codependency", "enmeshment": "enmeshment",
    "parasocial": "parasocial relationships", "one-sided": "one-sided love",
    "unrequited": "unrequited love", "obsession": "obsession",
    "infatuation": "infatuation", "lust": "lust", "longing": "longing",
    "heartbreak": "heartbreak", "grief": "grief", "loss": "loss",
    "moving on": "moving on", "closure": "closure",
    "second chance": "second chances", "forgiveness": "forgiveness",
    "reconciliation": "reconciliation", "estrangement": "estrangement",
    "boundaries": "your boundaries", "toxic relationship": "toxic relationships",
    "healthy relationship": "healthy relationships",
    "power dynamic": "power dynamics", "control": "control",
    "jealousy": "jealousy", "possessiveness": "possessiveness",
    "insecurity": "insecurity", "comparison": "comparison",

    "passion project": "your passion project", "dream job": "your dream job",
    "calling": "your calling", "vocation": "your vocation",
    "purpose driven": "being purpose-driven", "money driven": "being money-driven",
    "status driven": "status", "impact driven": "impact",
    "corporate ladder": "the corporate ladder", "glass ceiling": "the glass ceiling",
    "office politics": "office politics", "workplace culture": "workplace culture",
    "toxic workplace": "a toxic workplace", "psychological safety": "psychological safety",
    "mentorship": "mentorship", "sponsorship": "sponsorship",
    "networking": "networking", "connections": "your connections",
    "gatekeeping": "gatekeeping", "nepotism": "nepotism",
    "meritocracy": "meritocracy", "hard work": "hard work",
    "smart work": "working smart", "delegation": "delegation",
    "micromanagement": "micromanagement", "autonomy": "autonomy",
    "remote work": "remote work", "work-life balance": "work-life balance",
    "overtime": "overtime", "hustle": "the hustle",
    "burnout": "burnout", "quiet quitting": "quiet quitting",
    "great resignation": "the great resignation",
    "career change": "career changes", "pivot": "your pivot",
    "reinvention": "reinvention", "rebrand": "rebranding",
    "expertise": "expertise", "generalist": "being a generalist",
    "specialist": "being a specialist", "niche": "your niche",
    "thought leader": "thought leadership", "authority": "authority",
    "credibility": "credibility", "track record": "your track record",
    "portfolio": "your portfolio", "body of work": "your body of work",

    "privilege": "privilege", "oppression": "oppression",
    "systemic": "the system", "institutional": "institutions",
    "revolution": "revolution", "reform": "reform",
    "activism": "activism", "passivism": "passivism",
    "protest": "protest", "compliance": "compliance",
    "civil disobedience": "civil disobedience", "conformity": "conformity",
    "individualism": "individualism", "collectivism": "collectivism",
    "nationalism": "nationalism", "globalism": "globalism",
    "tribalism": "tribalism", "universalism": "universalism",
    "hierarchy": "hierarchy", "egalitarianism": "equality",
    "meritocracy": "meritocracy", "aristocracy": "aristocracy",
    "democracy": "democracy", "autocracy": "autocracy",
    "freedom of speech": "freedom of speech", "censorship": "censorship",
    "propaganda": "propaganda", "truth": "truth",
    "narrative control": "narrative control", "spin": "spin",
    "transparency": "transparency", "corruption": "corruption",
    "accountability": "accountability", "impunity": "impunity",
    "justice": "justice", "injustice": "injustice",
    "equality": "equality", "equity": "equity",
    "diversity": "diversity", "inclusion": "inclusion",
    "representation": "representation", "visibility": "visibility",
    "erasure": "erasure", "recognition": "recognition",
    "belonging": "belonging", "othering": "othering",

    "free will": "free will", "determinism": "determinism",
    "fate": "fate", "choice": "choice", "responsibility": "responsibility",
    "absurdism": "absurdism", "existentialism": "existentialism",
    "nihilism": "nihilism", "hedonism": "hedonism", "stoicism": "stoicism",
    "epicureanism": "epicureanism", "utilitarianism": "utilitarianism",
    "pragmatism": "pragmatism", "idealism": "idealism", "realism": "realism",
    "relativism": "relativism", "absolutism": "absolutism",
    "subjectivity": "subjectivity", "objectivity": "objectivity",
    "perspective": "perspective", "perception": "perception",
    "bias": "your biases", "assumption": "your assumptions",
    "belief system": "your belief system", "worldview": "your worldview",
    "paradigm": "your paradigm", "framework": "your framework",
    "lens": "the lens you see through", "filter": "your filters",
    "cognitive dissonance": "cognitive dissonance",
    "confirmation bias": "confirmation bias",
    "dunning kruger": "the dunning-kruger effect",
    "impermanence": "impermanence", "legacy": "your legacy",
    "impact": "your impact", "footprint": "your footprint",
    "contribution": "your contribution", "service": "service",
    "meaning": "meaning", "purpose": "purpose", "reason": "your reason",
    "why": "your why", "north star": "your north star",
    "compass": "your moral compass", "anchor": "your anchor",
    "foundation": "your foundation", "pillar": "your pillars",
    "core": "your core", "essence": "your essence",
    "nature": "your nature", "nurture": "nurture",
    "origin": "your origin", "beginning": "your beginning",
    "end": "your end", "middle": "where you are now",

    "hustle porn": "hustle porn", "grind": "the grind",
    "rise and grind": "rise and grind", "no days off": "having no days off",
    "sleep when dead": "sleeping when you're dead",
    "soft life": "the soft life", "slow living": "slow living",
    "intentional living": "intentional living", "conscious living": "conscious living",
    "simple living": "simple living", "frugality": "frugality",
    "excess": "excess", "luxury": "luxury", "deprivation": "deprivation",
    "gratitude practice": "your gratitude practice",
    "journaling": "journaling", "therapy": "therapy",
    "self help": "self-help", "personal development": "personal development",
    "life coaching": "life coaching", "mentoring": "mentoring",
    "accountability partner": "your accountability partner",
    "vision board": "your vision board", "goal setting": "goal setting",
    "morning routine": "your morning routine", "night routine": "your night routine",
    "habit stacking": "habit stacking", "systems": "your systems",
    "environment design": "environment design", "nudge": "nudges",
    "willpower": "willpower", "temptation bundling": "temptation bundling",
    "delayed gratification": "delayed gratification",
    "instant gratification": "instant gratification",
    "long game": "playing the long game", "short game": "playing the short game",
    "patience": "patience", "urgency": "urgency",
    "consistency": "consistency", "intensity": "intensity",
    "volume": "volume", "quality": "quality",
    "quantity": "quantity", "frequency": "frequency",
    "sustainability": "sustainability", "longevity": "longevity",
    "sprint": "sprinting", "marathon": "running a marathon",
    "pace": "your pace", "speed": "speed", "direction": "direction",
    "focus": "focus", "distraction": "distraction",
    "multitasking": "multitasking", "deep work": "deep work",
    "shallow work": "shallow work", "busy": "being busy",
    "productive": "productivity", "efficient": "efficiency",
    "effective": "effectiveness", "output": "your output",
    "input": "your input", "process": "your process",
    "result": "your results", "outcome": "your outcomes",
    "consequence": "consequences", "cause": "your cause",
    "effect": "your effect", "ripple": "your ripple effect",
    "butterfly effect": "the butterfly effect",
    "compounding": "compounding", "snowball": "the snowball effect",
    "tipping point": "the tipping point", "inflection point": "inflection points",
    "breakthrough": "your breakthrough", "barrier": "your barriers",
    "ceiling": "your ceiling", "floor": "your floor",
    "limit": "your limits", "potential": "your potential",
    "ceiling": "your ceiling", "horizon": "your horizon",
    "possibility": "possibility", "impossibility": "impossibility",
    "probability": "probability", "certainty": "certainty",
    "doubt": "doubt", "conviction": "conviction",
    "commitment": "commitment", "wavering": "wavering",
    "resolve": "resolve", "surrender": "surrender",
    "fight": "fighting", "flight": "flight", "freeze": "freezing",
    "fawn": "fawning", "adapt": "adaptability", "resist": "resistance",
    "persist": "persistence", "desist": "giving up",
    "pivot": "pivoting", "stay the course": "staying the course",
    "experiment": "experimentation", "iterate": "iteration",
    "test": "testing", "learn": "learning", "unlearn": "unlearning",
    "relearn": "relearning", "evolve": "evolving", "stagnate": "stagnation",
    "regress": "regression", "progress": "progress",
    "transformation": "transformation", "metamorphosis": "metamorphosis",

    "argent": "money", "richesse": "wealth", "succès": "success",
    "gloire": "glory", "pouvoir": "power", "statut": "status",
    "honneur": "honor", "respect": "respect", "dignité": "dignity",
    "famille": "family", "amour": "love", "amitié": "friendship",
    "amis": "your friends", "parents": "your parents", "enfants": "your children",
    "santé": "health", "beauté": "beauty", "corps": "your body",
    "travail": "work", "carrière": "career", "éducation": "your education",
    "connaissance": "knowledge", "sagesse": "wisdom", "talent": "talent",
    "rêves": "your dreams", "objectifs": "your goals", "avenir": "your future",
    "passé": "your past", "souvenirs": "your memories", "espoir": "hope",
    "liberté": "freedom", "choix": "choice", "destin": "destiny",
    "chance": "luck", "opportunité": "opportunity", "persévérance": "persistence",
    "courage": "courage", "confiance": "confidence", "fierté": "pride",
    "humilité": "humility", "gentillesse": "kindness", "honnêteté": "honesty",
    "loyauté": "loyalty", "confiance": "trust", "jalousie": "jealousy",
    "peur": "fear", "douleur": "pain", "solitude": "loneliness",
    "bonheur": "happiness", "paix": "peace", "sens": "meaning",
    "but": "purpose", "âme": "your soul", "identité": "identity",
    "culture": "culture", "racines": "your roots", "langue": "language",
    "foyer": "home", "appartenance": "belonging", "société": "society",
    "règles": "rules", "autorité": "authority", "changement": "change",
    "croissance": "growth", "progrès": "progress", "créativité": "creativity",
    "art": "art", "musique": "music", "temps": "time",
    "âge": "age", "mort": "death", "vie": "life",
    "existence": "existence", "vérité": "truth", "moralité": "morality",
    "justice": "justice", "égalité": "equality", "sacrifice": "sacrifice",
    "dévouement": "dedication", "responsabilité": "responsibility",
    "pression": "pressure", "attentes": "expectations", "normes": "standards",
    "perfection": "perfection", "échec": "failure", "victoire": "victory",
    "compétition": "competition", "réussite": "achievement", "gloire": "glory",
    "influence": "influence", "leadership": "leadership", "équipe": "your team",
    "contrôle": "control", "force": "strength", "volonté": "willpower",
    "passion": "passion", "obsession": "obsession", "habitudes": "your habits",
    "discipline": "discipline", "ego": "your ego", "valeurs": "your values",
    "caractère": "character", "réputation": "reputation",

    "geld": "money", "reichtum": "wealth", "erfolg": "success",
    "ruhm": "fame", "macht": "power", "status": "status",
    "ehre": "honor", "respekt": "respect", "würde": "dignity",
    "familie": "family", "liebe": "love", "freundschaft": "friendship",
    "freunde": "your friends", "eltern": "your parents", "kinder": "your children",
    "gesundheit": "health", "schönheit": "beauty", "körper": "your body",
    "arbeit": "work", "karriere": "career", "bildung": "your education",
    "wissen": "knowledge", "weisheit": "wisdom", "talent": "talent",
    "träume": "your dreams", "ziele": "your goals", "zukunft": "your future",
    "vergangenheit": "your past", "erinnerungen": "your memories", "hoffnung": "hope",
    "freiheit": "freedom", "wahl": "choice", "schicksal": "destiny",
    "glück": "luck", "gelegenheit": "opportunity", "ausdauer": "persistence",
    "mut": "courage", "selbstvertrauen": "confidence", "stolz": "pride",
    "demut": "humility", "güte": "kindness", "ehrlichkeit": "honesty",
    "loyalität": "loyalty", "vertrauen": "trust", "eifersucht": "jealousy",
    "angst": "fear", "schmerz": "pain", "einsamkeit": "loneliness",
    "glück": "happiness", "frieden": "peace", "sinn": "meaning",
    "zweck": "purpose", "seele": "your soul", "identität": "identity",
    "kultur": "culture", "wurzeln": "your roots", "sprache": "language",
    "heimat": "home", "zugehörigkeit": "belonging", "gesellschaft": "society",
    "regeln": "rules", "autorität": "authority", "wandel": "change",
    "wachstum": "growth", "fortschritt": "progress", "kreativität": "creativity",
    "kunst": "art", "musik": "music", "zeit": "time",
    "alter": "age", "tod": "death", "leben": "life",
    "existenz": "existence", "wahrheit": "truth", "moral": "morality",
    "gerechtigkeit": "justice", "gleichheit": "equality", "opfer": "sacrifice",
    "hingabe": "dedication", "verantwortung": "responsibility",
    "druck": "pressure", "erwartungen": "expectations", "standards": "standards",
    "perfektion": "perfection", "scheitern": "failure", "sieg": "victory",
    "wettbewerb": "competition", "leistung": "achievement", "ruhm": "glory",
    "einfluss": "influence", "führung": "leadership", "team": "your team",
    "kontrolle": "control", "stärke": "strength", "willenskraft": "willpower",
    "leidenschaft": "passion", "besessenheit": "obsession", "gewohnheiten": "your habits",
    "disziplin": "discipline", "ego": "your ego", "werte": "your values",
    "charakter": "character", "ruf": "reputation",

    "お金": "money", "富": "wealth", "成功": "success",
    "名声": "fame", "権力": "power", "地位": "status",
    "名誉": "honor", "尊敬": "respect", "尊厳": "dignity",
    "家族": "family", "愛": "love", "友情": "friendship",
    "友達": "your friends", "親": "your parents", "子供": "your children",
    "健康": "health", "美しさ": "beauty", "体": "your body",
    "仕事": "work", "キャリア": "career", "教育": "your education",
    "知識": "knowledge", "知恵": "wisdom", "才能": "talent",
    "夢": "your dreams", "目標": "your goals", "未来": "your future",
    "過去": "your past", "思い出": "your memories", "希望": "hope",
    "自由": "freedom", "選択": "choice", "運命": "destiny",
    "運": "luck", "チャンス": "opportunity", "忍耐": "persistence",
    "勇気": "courage", "自信": "confidence", "誇り": "pride",
    "謙虚": "humility", "優しさ": "kindness", "正直": "honesty",
    "忠誠": "loyalty", "信頼": "trust", "嫉妬": "jealousy",
    "恐れ": "fear", "痛み": "pain", "孤独": "loneliness",
    "幸せ": "happiness", "平和": "peace", "意味": "meaning",
    "目的": "purpose", "魂": "your soul", "アイデンティティ": "identity",
    "文化": "culture", "ルーツ": "your roots", "言語": "language",
    "家": "home", "帰属感": "belonging", "社会": "society",
    "ルール": "rules", "権威": "authority", "変化": "change",
    "成長": "growth", "進歩": "progress", "創造性": "creativity",
    "芸術": "art", "音楽": "music", "時間": "time",
    "年齢": "age", "死": "death", "生命": "life",
    "存在": "existence", "真実": "truth", "道徳": "morality",
    "正義": "justice", "平等": "equality", "犠牲": "sacrifice",
    "献身": "dedication", "責任": "responsibility",
    "プレッシャー": "pressure", "期待": "expectations", "基準": "standards",
    "完璧": "perfection", "失敗": "failure", "勝利": "victory",
    "競争": "competition", "達成": "achievement", "栄光": "glory",
    "影響力": "influence", "リーダーシップ": "leadership", "チーム": "your team",
    "コントロール": "control", "強さ": "strength", "意志力": "willpower",
    "情熱": "passion", "執着": "obsession", "習慣": "your habits",
    "規律": "discipline", "エゴ": "your ego", "価値観": "your values",
    "キャラクター": "character", "評判": "reputation",

    "dinheiro": "money", "riqueza": "wealth", "sucesso": "success",
    "fama": "fame", "poder": "power", "status": "status",
    "honra": "honor", "respeito": "respect", "dignidade": "dignity",
    "família": "family", "amor": "love", "amizade": "friendship",
    "amigos": "your friends", "pais": "your parents", "filhos": "your children",
    "saúde": "health", "beleza": "beauty", "corpo": "your body",
    "trabalho": "work", "carreira": "career", "educação": "your education",
    "conhecimento": "knowledge", "sabedoria": "wisdom", "talento": "talent",
    "sonhos": "your dreams", "metas": "your goals", "futuro": "your future",
    "passado": "your past", "memórias": "your memories", "esperança": "hope",
    "liberdade": "freedom", "escolha": "choice", "destino": "destiny",
    "sorte": "luck", "oportunidade": "opportunity", "persistência": "persistence",
    "coragem": "courage", "confiança": "confidence", "orgulho": "pride",
    "humildade": "humility", "bondade": "kindness", "honestidade": "honesty",
    "lealdade": "loyalty", "confiança": "trust", "ciúme": "jealousy",
    "medo": "fear", "dor": "pain", "solidão": "loneliness",
    "felicidade": "happiness", "paz": "peace", "significado": "meaning",
    "propósito": "purpose", "alma": "your soul", "identidade": "identity",
    "cultura": "culture", "raízes": "your roots", "idioma": "language",
    "lar": "home", "pertencimento": "belonging", "sociedade": "society",
    "regras": "rules", "autoridade": "authority", "mudança": "change",
    "crescimento": "growth", "progresso": "progress", "criatividade": "creativity",
    "arte": "art", "música": "music", "tempo": "time",
    "idade": "age", "morte": "death", "vida": "life",
    "existência": "existence", "verdade": "truth", "moralidade": "morality",
    "justiça": "justice", "igualdade": "equality", "sacrifício": "sacrifice",
    "dedicação": "dedication", "responsabilidade": "responsibility",
    "pressão": "pressure", "expectativas": "expectations", "padrões": "standards",
    "perfeição": "perfection", "fracasso": "failure", "vitória": "victory",
    "competição": "competition", "conquista": "achievement", "glória": "glory",
    "influência": "influence", "liderança": "leadership", "equipe": "your team",
    "controle": "control", "força": "strength", "força de vontade": "willpower",
    "paixão": "passion", "obsessão": "obsession", "hábitos": "your habits",
    "disciplina": "discipline", "ego": "your ego", "valores": "your values",
    "caráter": "character", "reputação": "reputation",

    "المال": "money", "الثروة": "wealth", "النجاح": "success",
    "الشهرة": "fame", "القوة": "power", "المكانة": "status",
    "الشرف": "honor", "الاحترام": "respect", "الكرامة": "dignity",
    "العائلة": "family", "الحب": "love", "الصداقة": "friendship",
    "الأصدقاء": "your friends", "الوالدان": "your parents", "الأبناء": "your children",
    "الصحة": "health", "الجمال": "beauty", "الجسم": "your body",
    "العمل": "work", "المسيرة المهنية": "career", "التعليم": "your education",
    "المعرفة": "knowledge", "الحكمة": "wisdom", "الموهبة": "talent",
    "الأحلام": "your dreams", "الأهداف": "your goals", "المستقبل": "your future",
    "الماضي": "your past", "الذكريات": "your memories", "الأمل": "hope",
    "الحرية": "freedom", "الاختيار": "choice", "القدر": "destiny",
    "الحظ": "luck", "الفرصة": "opportunity", "المثابرة": "persistence",
    "الشجاعة": "courage", "الثقة": "confidence", "الفخر": "pride",
    "التواضع": "humility", "اللطف": "kindness", "الصدق": "honesty",
    "الولاء": "loyalty", "الثقة": "trust", "الغيرة": "jealousy",
    "الخوف": "fear", "الألم": "pain", "الوحدة": "loneliness",
    "السعادة": "happiness", "السلام": "peace", "المعنى": "meaning",
    "الهدف": "purpose", "الروح": "your soul", "الهوية": "identity",
    "الثقافة": "culture", "الجذور": "your roots", "اللغة": "language",
    "الوطن": "home", "الانتماء": "belonging", "المجتمع": "society",
    "القواعد": "rules", "السلطة": "authority", "التغيير": "change",
    "النمو": "growth", "التقدم": "progress", "الإبداع": "creativity",
    "الفن": "art", "الموسيقى": "music", "الوقت": "time",
    "العمر": "age", "الموت": "death", "الحياة": "life",
    "الوجود": "existence", "الحقيقة": "truth", "الأخلاق": "morality",
    "العدالة": "justice", "المساواة": "equality", "التضحية": "sacrifice",
    "التفاني": "dedication", "المسؤولية": "responsibility",
    "الضغط": "pressure", "التوقعات": "expectations", "المعايير": "standards",
    "الكمال": "perfection", "الفشل": "failure", "النصر": "victory",
    "المنافسة": "competition", "الإنجاز": "achievement", "المجد": "glory",
    "التأثير": "influence", "القيادة": "leadership", "الفريق": "your team",
    "السيطرة": "control", "القوة": "strength", "قوة الإرادة": "willpower",
    "الشغف": "passion", "الهوس": "obsession", "العادات": "your habits",
    "الانضباط": "discipline", "الأنا": "your ego", "القيم": "your values",
    "الشخصية": "character", "السمعة": "reputation",
}

VERB_CONCEPTS = {
    "play": "playing", "playing": "playing",
    "run": "running", "running": "running",
    "fight": "fighting", "fighting": "fighting",
    "help": "helping others", "helping": "helping others",
    "create": "creating", "creating": "creating",
    "build": "building", "building": "building",
    "lead": "leading", "leading": "leading",
    "teach": "teaching", "teaching": "teaching",
    "learn": "learning", "learning": "learning",
    "perform": "performing", "performing": "performing",
    "compete": "competing", "competing": "competing",
    "win": "winning", "winning": "winning",
    "lose": "losing", "losing": "losing",
    "talk": "talking", "talking": "talking",
    "listen": "listening", "listening": "listening",
    "give": "giving", "giving": "giving",
    "take": "taking", "taking": "taking",
    "show": "showing off", "showing": "showing off",
    "control": "control", "controlling": "control",
    "protect": "protecting", "protecting": "protecting",
}


def extract_power(message_text: str) -> str:
    text = message_text.lower()
    text = re.sub(r"https?://\S+", "", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"[^\w\s']", " ", text)
    words = text.split()

    for length in [3, 2, 1]:
        for i in range(len(words) - length + 1):
            phrase = " ".join(words[i:i+length])
            if phrase in CONCEPT_MAP:
                return CONCEPT_MAP[phrase]

    for word in words:
        if word in VERB_CONCEPTS:
            return VERB_CONCEPTS[word]

    candidates = [w for w in words if w not in STOPWORDS and len(w) >= 4 and w.isalpha()]
    if candidates:
        freq = Counter(candidates)
        return max(candidates, key=lambda w: (freq[w], len(w)))

    # Vervang je huidige fallbacks lijst met deze
    # Zoek in je bot naar: fallbacks = [ en vervang de hele lijst

    fallbacks = [
        # Identiteit
        "what you know", "what you have", "what others think of you",
        "your past", "your image", "your certainty", "your name",
        "your story", "your reputation", "your title", "your role",
        "your label", "your mask", "your facade", "your reflection",
        "your shadow", "your ego", "your pride", "your shame",
        "your secrets", "your lies", "your excuses", "your assumptions",
        "your beliefs", "your opinions", "your perspective", "your narrative",
        "your identity", "your self-image", "your self-worth", "your confidence",
        "your insecurities", "your fears", "your doubts", "your regrets",
        "your grudges", "your biases", "your expectations", "your standards",

        # Bezittingen & status
        "what you own", "what you've earned", "what you've built",
        "what you've lost", "what you've been given", "what you've taken",
        "your possessions", "your achievements", "your awards", "your trophies",
        "your titles", "your medals", "your certificates", "your degrees",
        "your salary", "your savings", "your investments", "your assets",
        "your house", "your car", "your clothes", "your phone",
        "your followers", "your likes", "your views", "your clout",
        "your platform", "your reach", "your influence", "your brand",
        "your status", "your rank", "your position", "your privilege",

        # Relaties
        "the people who need you", "the people who love you",
        "the people who fear you", "the people who follow you",
        "the people who left you", "the people who stayed",
        "your relationships", "your connections", "your allies",
        "your enemies", "your rivals", "your fans", "your haters",
        "your family", "your friends", "your partner", "your community",
        "their approval", "their validation", "their attention", "their respect",
        "their fear", "their admiration", "their loyalty", "their trust",

        # Vermogen & talent
        "your talent", "your skill", "your ability", "your intelligence",
        "your creativity", "your charisma", "your charm", "your wit",
        "your discipline", "your willpower", "your ambition", "your drive",
        "your hustle", "your grind", "your persistence", "your resilience",
        "your potential", "your gifts", "your strengths", "your advantages",
        "your experience", "your expertise", "your knowledge", "your wisdom",
        "your voice", "your words", "your ideas", "your vision",
        "your art", "your music", "your craft", "your work",

        # Emoties & innerlijk
        "your anger", "your pain", "your sadness", "your joy",
        "your love", "your hate", "your hope", "your despair",
        "your passion", "your obsession", "your addiction", "your comfort",
        "your trauma", "your healing", "your growth", "your wounds",
        "your dreams", "your nightmares", "your memories", "your fantasies",
        "your longing", "your emptiness", "your fullness", "your hunger",
        "your silence", "your noise", "your chaos", "your peace",
        "your light", "your darkness", "your warmth", "your coldness",

        # Tijd & verandering
        "your past", "your future", "your youth", "your age",
        "your beginnings", "your endings", "your failures", "your victories",
        "your progress", "your stagnation", "your momentum", "your stillness",
        "the time you've spent", "the time you've wasted", "the time you have left",
        "what you used to be", "what you're becoming", "what you once had",
        "what you've sacrificed", "what you've survived", "what you've forgotten",

        # Filosofisch & abstract
        "your certainty", "your uncertainty", "your truth", "your illusions",
        "your purpose", "your meaning", "your direction", "your path",
        "your faith", "your doubt", "your beliefs", "your principles",
        "your morals", "your values", "your ethics", "your code",
        "your karma", "your fate", "your luck", "your choices",
        "your freedom", "your chains", "your limitations", "your potential",
        "the idea of you", "the version of you they know",
        "the version of you that never existed",
        "the life you imagined", "the life you're living",
        "the gap between who you are and who you want to be",
        "the distance between your words and your actions",
        "the silence between your thoughts",
        "everything you've been pretending not to feel",
        "the part of you that no one sees",
        "the part of you that everyone sees",
        "what you show the world", "what you hide from the world",
        "what you tell yourself at night", "what you refuse to admit",
        "what keeps you going", "what holds you back",
        "what makes you feel alive", "what makes you feel empty",
        "what you're running from", "what you're running towards",
        "what you'd be without the noise", "what remains when everything is stripped away",
        "who you are when no one is watching",
        "who you are when everything goes wrong",
        "who you are when no one is clapping",
    ]
    return fallbacks[len(message_text) % len(fallbacks)]


def build_question(power: str) -> str:
    return f"If **{power}** is your power, what are you without it?"


# ──────────────────────────────────────────────
# BOT SETUP
# ──────────────────────────────────────────────

intents = discord.Intents.default()
intents.message_content = True

client = discord.Client(intents=intents)
tree = app_commands.CommandTree(client)

guild_obj = discord.Object(id=GUILD_ID) if GUILD_ID else None


# ──────────────────────────────────────────────
# APP COMMANDS  (rechtermuisklik → Apps)
# ──────────────────────────────────────────────

@tree.context_menu(name="Philosophize")
@app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
@app_commands.allowed_installs(guilds=True, users=True)
async def philosophize_public(
    interaction: discord.Interaction,
    message: discord.Message,
):
    content = message.content.strip()

    if not content:
        await interaction.response.send_message(
            "❌ This message has no text to analyze.",
            ephemeral=True,
        )
        return

    power = extract_power(content)
    question = build_question(power)

    await interaction.response.send_message(question)


@tree.context_menu(name="Philosophize → DM")
@app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
@app_commands.allowed_installs(guilds=True, users=True)
async def philosophize_dm(
    interaction: discord.Interaction,
    message: discord.Message,
):
    """Sends the philosophical question to the user's DMs."""
    content = message.content.strip()

    if not content:
        await interaction.response.send_message(
            "❌ This message has no text to analyze.",
            ephemeral=True,
        )
        return

    power = extract_power(content)
    question = build_question(power)

    try:
        await interaction.user.send(
            f"**Philosophical question about a message from {message.author.display_name}:**\n"
            f"> {message.content[:200]}\n\n"
            f"{question}"
        )
        await interaction.response.send_message("📬 Check your DMs!", ephemeral=True)
    except discord.Forbidden:
        await interaction.response.send_message(
            "❌ I can't send you a DM. Please enable DMs for this server.",
            ephemeral=True,
        )


# ──────────────────────────────────────────────
# EVENTS
# ──────────────────────────────────────────────

@client.event
async def on_ready():
        await tree.sync()
        print(f"⚡ Commands gesync (instant)")
        if guild_obj:
            await tree.sync(guild=guild_obj)
            print(f"⚡ Commands gesync naar guild {GUILD_ID}")


@client.event
async def on_message(message: discord.Message):
    if message.author == client.user:
        return
    if message.channel.id != TARGET_CHANNEL_ID:
        return

    content = message.content.strip()
    if not content:
        return

    power = extract_power(content)
    question = build_question(power)
    await message.reply(question, mention_author=False)

@tree.command(name="philosophize", description="Socrates will philosophize about your concept")
@app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
@app_commands.allowed_installs(guilds=True, users=True)
async def philosophize_slash(interaction: discord.Interaction, tekst: str):
    power = extract_power(tekst)
    question = build_question(power)
    await interaction.response.send_message(question)


# ──────────────────────────────────────────────
# START
# ──────────────────────────────────────────────
if __name__ == "__main__":
    if TOKEN == "JOUW_BOT_TOKEN_HIER":
        print("❌ Vul je bot token in bij TOKEN!")
    else:
        client.run(TOKEN)
